version: '2'
services:
  mariadb:
    image: 'bitnami/mariadb:10.3'
    volumes:
      - 'mariadb_data:/bitnami'
    environment:
      - MARIADB_USER=bn_wordpress
      - MARIADB_DATABASE=bitnami_wordpress
      - ALLOW_EMPTY_PASSWORD=yes
  wordpress:
    image: 'bitnami/wordpress:5'
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - 'wordpress_data:/bitnami'
    depends_on:
      - mariadb
    environment:
      - MARIADB_HOST=mariadb
      - MARIADB_PORT_NUMBER=3306
      - WORDPRESS_DATABASE_USER=bn_wordpress
      - WORDPRESS_DATABASE_NAME=bitnami_wordpress
      - ALLOW_EMPTY_PASSWORD=yes
  code-server:
    image: 'codercom/code-server'
    ports:
      - '40:8443'
    volumes:
        - "${PWD}:/home/coder/project"
    environment:
      PASSWORD: ${PASSWORD}
    volumes_from:
      - 'wordpress'
    depends_on:
      - wordpress
    command: /bitnami/wordpress/wp-content/themes/twentynineteen
volumes:
  mariadb_data:
    driver: local
  wordpress_data:
    driver: local
